#TESTS POST, SCHEMA, MEDIA TYPE, REQUEST BODY


openapi: 3.0.0
info:
  title: Pet Store
  version: 1.0.0
paths:
  /pets:
    post:
      responses:
        '200':
          description: good job
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewPet"



components:
  schemas:
    Pet:
      allOf:
        - $ref: '#/components/schemas/NewPet'
        - required:
          - id
          properties:
            id:
              type: integer
              format: int64

    NewPet:
      required:
        - name  
      properties:
        name:
          type: string
        tag:
          type: string    

    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
