#TESTS HEADERS

openapi: 3.0.0
info:
  title: Pet Store
  version: 1.0.0
paths:
  /pets:
    get:
      responses:
        '200':
          description: array of pets

components:
  headers:
    myHeader:
      description: This is a useless header
    myOtherHeader:
      description: Second useless header
      schema:
        type: integer
