#TESTS LINKS

openapi: 3.0.0
info:
  title: Pet Store
  version: 1.0.0
paths:
  /pets:
    get:
      responses:
        '200':
          description: hurray

components:
  links:
    myLink:
      description: yay
